#!/bin/bash
cd /home/cweaver/noodlings


git fetch origin
#git stash
git merge '@{u}'
#git stash pop
gcc -O3 -o ../caw/stang stang.c &>drelmout
#../caw/rg64 409600 lorque > ../caw/aak
../caw/stang 100 12 0 >> drelmout
../caw/stang 100 13 0 >> drelmout
echo drok$(date +%Y%m%d%H%M) > ../caw/blep
git stage drelmout
git commit -F ../caw/blep drelmout
git push
