#!/bin/bash
cd /home/cweaver/noodlings

#waba
git fetch origin master
#git stash
git reset --hard origin/master
git config --global core.autocrlf false
#git stash pop
#gcc -O3 -o ../caw/latinjm latinjm/main.c 
../caw/latinjm 50 doublebubble >drelmout
echo drok$(date +%Y%m%d%H%M) > ../caw/blep
git stage drelmout
git commit -F ../caw/blep drelmout
git push
